### ISSUE TITLE
Error when computing `__len__` generalized index on `List` type

### ISSUE THREAD

**Issue by ralexstokes** [protolambda/remerkleable#20]
The following code fails when using the [`get_generalized_indices` function defined in the `consensus-specs`](https://github.com/ethereum/consensus-specs/blob/cdb6725275ea9aaa6d4a323c72be59cc34b458a3/pysetup/spec_builders/altair.py#L30):

```python
    index = get_generalized_index(List[uint8, 256], "__len__")
    print(index)
```

with:

```
    if key >= cls.limit():
TypeError: '>=' not supported between instances of 'str' and 'int'
```

from here: https://github.com/protolambda/remerkleable/blob/91ed092d08ef0ba5ab076f0a34b0b371623db728/remerkleable/complex.py#L464

I would think this method should be extended to avoid this check for the special key `__len__`. Happy to open a PR if this is the preferred route!

**Comment by protolambda** [comment]
PRs welcome! Thank you for looking into this.
